spring.application.name=ecommerce
server.port= 8080
spring.datasource.url=jdbc:postgressql://localhost:5434/ecom
spring.datasource.username=learnecom
spring.datasource.password=pgadmin123

Spring.datasource.driver-class-name=org.postgressql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true