spring.application.name=ecommerce 
spring.datasource.url=jdbc:postgressql://localhost:5432/ecom
spring.datasource.username=learncom
spring.datasource.password=pgadmin123

spring.jpa.hibernate.ddl-auto=update