spring.application.name=ecommerce
server.port= 8081

#Datasource
spring.datasource.url=jdbc:postgresql://localhost:5544/ecom
spring.datasource.username=learnecom
spring.datasource.password=pgadmin123

Spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true